# Set default image to podman, for docker builds.  
# We have to use this because for some reason the official docker image does not work.
image: quay.io/podman/stable

# This builds an image of the api, and pushes it to the docker repository.
build-api:
  stage: build
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[BUILD-API]/
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /\[NOTHING]/
      when: never
  script:
  
    # This set of instructions simply navigates to the road-trip-api and
    # road-trip-frontend folders and builds a docker image based on the
    # docker files it finds there. This assumes there is a file named
    # "Dockerfile" in each directory.
    - cd road-trip-api
    - chmod +x gradlew
    - podman build -t road-trip-api .
    - podman tag road-trip-api docker.io/kaase/road-trip-api:latest
    - echo $DOCKERUSER
    - echo $DOCKERKEY
    - podman login -u $DOCKERUSER -p $DOCKERKEY docker.io
    - podman push kaase/road-trip-api:latest

# This builds an image of the frontend, and pushes it to the docker repository.
build-frontend:
  stage: build
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[NOTHING]/
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /\[BUILD-FRONTEND]/
      when: always
    
  script:
    # This set of instructions simply navigates to the road-trip-api and
    # road-trip-frontend folders and builds a docker image based on the
    # docker files it finds there. This assumes there is a file named
    # "Dockerfile" in each directory.
    - cd road-trip-frontend
    - podman build -t road-trip-frontend .
    - podman tag road-trip-frontend docker.io/kaase/road-trip-frontend:latest
    - podman login -u $DOCKERUSER -p $DOCKERKEY docker.io
    - podman push kaase/road-trip-frontend:latest

# This deploys the built frontend image to the Kubernetes repository.
deploy-frontend:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  stage: deploy
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[NOTHING]/
      when: never
  script:
    - cd kubernetes
    - cd road-trip-api
    - kubectl apply -f road-trip-api-deployment.yaml
    - kubectl apply -f road-trip-api-service.yaml

# This deploys the built api image to the Kubernetes repository.
deploy-db:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  stage: deploy
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[DEPLOY-DB]/
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /\[NOTHING]/
      when: never
  script:
    - cd kubernetes
    - kubectl apply -f mysql.yaml

# This deploys the built api image to the Kubernetes repository.
deploy-api:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  stage: deploy
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[NOTHING]/
      when: never
  script:
    - cd kubernetes
    - cd road-trip-frontend
    - kubectl apply -f road-trip-frontend-deployment.yaml
    - kubectl apply -f road-trip-frontend-service.yaml
deploy-nginx:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  stage: deploy
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[NOTHING]/
      when: never
  script:
    - cd kubernetes
    - kubectl apply -f nginx.yaml

# This deploys the ingress controller, which regulates traffic to each service.
deploy-ingress:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  stage: deploy
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[NOTHING]/
      when: never
  script:
    - cd kubernetes
    - kubectl apply -f ingress-controller.yaml
.deploy-prod:
  stage: deploy
  script:
# This script simply runs the images that were built in the previous step.
# This assumes there is a file named "docker-compose.yml" in the root
# directory.

# If the frontend and backend are already running on the VM, we need to 
# stop them to free the port and delete them to free the container name
# before trying to start the new versions
    - podman container stop road-trip-frontend || true
    - podman container stop road-trip-api || true
    - podman rm road-trip-frontend || true
    - podman rm road-trip-api || true
    - podman compose up -d
    - podman run -dp 8080:8080 --name road-trip-api road-trip-api
    - podman run -dp 3000:3000 --name road-trip-frontend road-trip-frontend
# it is important you prune your docker repository after all containers
# are deployed. This is because all images used in the build stages are
# saved by docker; this can quickly consume a lot of memory after a few
# builds.
    - podman image prune -af
