---
# https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: road-trip-frontend
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
