apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
      tier: web
  template:
    metadata:
      labels:
        app: frontend
        tier: web
    spec:
      containers:
      - name: frontend
        image: docker.io/kaase/road-trip-frontend:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 900m
