---
# https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: road-trip-api
  ports:
    - port: 8080
  type: ClusterIP
