apiVersion: apps/v1
kind: Deployment
metadata:
  name: road-trip-api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
      tier: web
  template:
    metadata:
      labels:
        app: api
        tier: web
    spec:
      containers:
      - name: road-trip-api
        image: docker.io/kaase/road-trip-api:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
